### ISSUE TITLE
Issue with saving video

### ISSUE THREAD

**Issue by Marsataheri** [int-brain-lab/iblviewer#8]
I've never been able to save a video on iblviewer. When I click on export 360 video, or try to change the end angle for example, I get the error below:

`Traceback (most recent call last):

  File "/Users/mt/opt/anaconda3/envs/iblenv/lib/python3.9/site-packages/iblviewer/utils.py", line 184, in wrapper
    func(event_dict)

  File "/Users/mt/opt/anaconda3/envs/iblenv/lib/python3.9/site-packages/iblviewer/application.py", line 867, in handle_left_mouse_release
    if np.linalg.norm(last - picked3d) > 0:

TypeError: unsupported operand type(s) for -: 'NoneType' and 'float'`

Also, I'm wondering whether this video saving feature would also allow saving an image? If so, would the video duration need to be set to 0, or 1? Thank you!

**Comment by nantille** [comment]
Thanks for reporting this. Actually this happens when you are not in Qt UI. It works fine when you start iblviewer with the launcher (shorcut `iblviewer` equivalent to `iblviewer -ui 1` which is Qt). You have more options with Qt by the way (like exporting an image). This is due to the limitations of the embed UI. But if you're using the viewer in a Jupyter notebook, you probably need the embed UI.

So  you may update the viewer with `pip install -U git+https://github.com/int-brain-lab/iblviewer.git`. I've added an export image button. It will export an image twice the size of your current window (without UI except outline, marker and scale bar if you have them activated, see 'Scene' params in embed mode).
